<a href="https://colab.research.google.com/github/ashia-002/python-oop-pandas-numpy/blob/main/Pandas_%26_Python_for_Data_Analysis/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

**Importing the dataframe**

In [18]:
df = pd.read_csv('/content/sample_data/california_housing_test.csv')
df.head(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
5,-119.56,36.51,37.0,1018.0,213.0,663.0,204.0,1.6635,67000.0
6,-121.43,38.63,43.0,1009.0,225.0,604.0,218.0,1.6641,67000.0
7,-120.65,35.48,19.0,2310.0,471.0,1341.0,441.0,3.2250,166900.0
8,-122.84,38.40,15.0,3080.0,617.0,1446.0,599.0,3.6696,194400.0
9,-118.02,34.08,31.0,2402.0,632.0,2830.0,603.0,2.3333,164200.0

**How many elements the data frame has**

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB

In [6]:
df.shape

(3000, 9)

**What is the population value of the forth row**

In [8]:
df.loc[4, "population"] #row, column

np.float64(850.0)

**What is the highest possible population**

In [9]:
df['population'].max()

11935.0

In [10]:
df.max() # maximum value of all columns

longitude               -114.4900
latitude                  41.9200
housing_median_age        52.0000
total_rooms            30450.0000
total_bedrooms          5419.0000
population             11935.0000
households              4930.0000
median_income             15.0001
median_house_value    500001.0000
dtype: float64

**What is the latitude of 4, 6, 8, 10 row**

In [14]:
df.loc[[
    4,
    6,
    8,
    10
    ], 'latitude']

4     36.33
6     38.63
8     38.40
10    33.98
Name: latitude, dtype: float64

**What is the median_house_value of 564 population**

In [15]:
df.sort_values(by=['population'], ascending=False)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
978,-121.53,38.48,5.0,27870.0,5027.0,11935.0,4855.0,4.8811,212200.0
2186,-116.14,34.45,12.0,8796.0,1721.0,11139.0,1680.0,2.2612,137500.0
1146,-117.27,33.15,4.0,23915.0,4135.0,10877.0,3958.0,4.6357,244900.0
2429,-117.20,33.58,2.0,30450.0,5033.0,9419.0,3197.0,4.5936,174300.0
1597,-117.12,33.49,4.0,21988.0,4055.0,8824.0,3252.0,3.9963,191100.0
...,...,...,...,...,...,...,...,...,...
1355,-117.11,32.66,52.0,25.0,5.0,14.0,9.0,1.6250,118800.0
2494,-118.44,34.04,49.0,32.0,7.0,14.0,7.0,2.1875,225000.0
740,-117.12,32.66,52.0,16.0,4.0,8.0,3.0,1.1250,60000.0
1115,-116.95,33.86,1.0,6.0,2.0,8.0,2.0,1.6250,55000.0
2640,-114.62,33.62,26.0,18.0,3.0,5.0,3.0,0.5360,275000.0

In [17]:
df[df['population'] == 564]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
11,-119.12,35.85,37.0,736.0,166.0,564.0,138.0,2.4167,58300.0
1985,-122.47,37.72,47.0,1176.0,286.0,564.0,258.0,3.2059,350000.0

**What is the most number of bedrooms**

In [20]:
df['total_bedrooms'].mode()

0    314.0
Name: total_bedrooms, dtype: float64

In [21]:
df['total_bedrooms'].value_counts().head()

total_bedrooms
314.0    15
270.0    12
299.0    11
459.0    10
493.0    10
Name: count, dtype: int64

**For the most number of bedrooms what are the total rooms**

In [28]:
df[df['total_bedrooms'] == 314.0][['total_rooms', 'total_bedrooms']].head(5)

     total_rooms  total_bedrooms
109       1514.0           314.0
197       1276.0           314.0
310       1595.0           314.0
412       1605.0           314.0
524       1005.0           314.0

In [29]:
df.loc[df['total_bedrooms'] == 314.0, ['total_rooms', 'total_bedrooms']].head(5)

     total_rooms  total_bedrooms
109       1514.0           314.0
197       1276.0           314.0
310       1595.0           314.0
412       1605.0           314.0
524       1005.0           314.0